apiVersion: v1
kind: Pod
metadata:
  name: nginx-container
  labels: 
    app: nginx
    tier: frontend
spec:
  containers:
  - name: sonarqube
    image: sonarqube:latest
    ports:
    - containerPort: 9000