apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: development
spec:
  clusterIP: None  # Makes it a headless service
  selector:
    app: nginx
  ports:
  - name: web
    port: 80
    targetPort: 80