apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
  namespace: dev
spec:
  selector:
    matchLabels:
      app: monitoring-nginx
  template:
    metadata:
      labels:
        app: monitoring-nginx
    spec:
      containers:
      - name: monitoring-nginx
        image: nginx