apiVersion: v1
kind: Pod
metadata:
  name: nginx-labelnode
  namespace: dev
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    size: Large