apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-develop
  namespace: dev
subjects:
- kind: User
  name: v.lakshmi@soprasteria.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: Ram
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: Casur
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Developer
  apiGroup: rbac.authorization.k8s.io